<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login with Data</title>
    <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet" />
</head>

<body>
    <div class="relative flex min-h-screen flex-col justify-center overflow-hidden py-6 bg-gray-50">
        <div
            class="relative bg-white px-6 pt-5 pb-5 shadow-xl ring-1 ring-gray-900/5 sm:mx-auto sm:max-w-lg sm:rounded-lg sm:px-10">
            <div class="mx-auto max-w-md">
                <h2 class="text-3xl text-center font-bold leading-tight">
                    Registration Form
                </h2>
                <div class="divide-y divide-gray-300/50">
                    <div class="space-y-6 py-8 text-base leading-7 text-gray-600">
                        <form id="user-form" class="mb-5">
                            <label for="name"
                                class="text-md w-40 inline-block font-medium leading-5 text-gray-700">Name</label>
                            <input required type="text" id="name" name="name"
                                class="bg-gray-100 inline-block rounded-lg shadow-md px-4 py-3 mb-5 text-base leading-6 placeholder-gray-500 focus:outline-none focus:placeholder-g focus:border-pink-500 focus:ring-pink-500"
                                placeholder="Enter full name" />

                            <label for="email"
                                class="text-md w-40 inline-block font-medium leading-5 text-gray-700">Email</label>
                            <input required type="email" id="email" name="email"
                                class="bg-gray-100 inline-block rounded-lg shadow-md px-4 py-3 mb-5 text-base leading-6 placeholder-gray-500 focus:outline-none focus:placeholder-g focus:border-pink-500 focus:ring-pink-500"
                                placeholder="Enter email" />

                            <label for="password"
                                class="text-md w-40 inline-block font-medium leading-5 text-gray-700">Password</label>
                            <input required type="password" id="password" name="password"
                                class="bg-gray-100 inline-block rounded-lg shadow-md px-4 py-3 mb-5 text-base leading-6 placeholder-gray-500 focus:outline-none focus:placeholder-g focus:border-pink-500 focus:ring-pink-500"
                                placeholder="Enter password" />

                            <label for="dob" class="text-md w-40 inline-block font-medium leading-5 text-gray-700">Date
                                of Birth</label>
                            <input required type="date" id="dob" name="dob" min="1967-09-21" max="2004-11-21"
                                class="bg-gray-100 inline-block rounded-lg shadow-md px-4 py-3 mb-5 text-base leading-6 placeholder-gray-500 focus:outline-none focus:placeholder-g focus:border-pink-500 focus:ring-pink-500" />

                            <label for="acceptTerms"
                                class="text-md inline-block font-medium leading-5 text-gray-700">Accept
                                Terms &
                                Conditions</label>
                            <input type="checkbox" id="acceptTerms" name="acceptTerms" required
                                class="bg-gray-100 inline-block rounded-lg shadow-md px-4 py-3 mb-5 text-base leading-6 placeholder-gray-500 focus:outline-none focus:placeholder-g" />

                            <button type="submit"
                                class="w-fit rounded-lg shadow-lg px-8 py-4 bg-green-500 text-white hover:bg-green-400 focus:outline-none focus:shadow-outline transition duration-300">
                                Submit
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="mt-8 mx-auto max-w-md">
            <h2 class="text-2xl font-bold mb-4">User Entries</h2>
            <table class="min-w-full divide-y divide-gray-200">
                <thead class="bg-gray-50">
                    <tr>
                        <th scope="col"
                            class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Name
                        </th>
                        <th scope="col"
                            class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Email
                        </th>
                        <th scope="col"
                            class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Password
                        </th>
                        <th scope="col"
                            class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Dob
                        </th>
                        <th scope="col"
                            class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Accepted
                        </th>
                    </tr>
                </thead>
                <tbody id="user-entries-table-body">
                </tbody>
            </table>
        </div>
    </div>
    <script>
        let userForm = document.getElementById("user-form");
        let userEntries = [];

        // Load entries from localStorage on page load
        window.addEventListener("load", () => {
            const storedEntries = localStorage.getItem("user-entries");
            if (storedEntries) {
                userEntries = JSON.parse(storedEntries);
                updateTable();
            }
        });

        const saveUserForm = (event) => {
            event.preventDefault();
            const name = document.getElementById("name").value;
            const email = document.getElementById("email").value;
            const password = document.getElementById("password").value;
            const dob = document.getElementById("dob").value;
            const acceptedTermsAndconditions =
                document.getElementById("acceptTerms").checked;

            const entry = {
                name,
                email,
                password,
                dob,
                acceptedTermsAndconditions,
            };
            userEntries.push(entry);

            updateTable(); // Call the function to update the table
            localStorage.setItem("user-entries", JSON.stringify(userEntries));

            // Clear the form fields after submission
            userForm.reset();
        };

        userForm.addEventListener("submit", saveUserForm);

        // Function to update the table with user entries
        const updateTable = () => {
            const tableBody = document.getElementById("user-entries-table-body");
            tableBody.innerHTML = ""; // Clear existing entries

            userEntries.forEach((entry) => {
                const row = document.createElement("tr");
                row.innerHTML = `
          <td class="px-6 py-4 whitespace-nowrap">${entry.name}</td>
          <td class="px-6 py-4 whitespace-nowrap">${entry.email}</td>
          <td class="px-6 py-4 whitespace-nowrap">${entry.password}</td>
          <td class="px-6 py-4 whitespace-nowrap">${entry.dob}</td>
          <td class="px-6 py-4 whitespace-nowrap">${entry.acceptedTermsAndconditions ? "Yes" : "No"
                    }</td>
        `;
                tableBody.appendChild(row);
            });
        };
    </script>
</body>

</html>
